"""initial

Revision ID: 41d6850e79a1
Revises: 
Create Date: 2026-05-04 10:46:09.877520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d6850e79a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_barang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=64), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('master_kondisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=64), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('master_ruang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=64), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('master_satuan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=64), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('inventory_item',
    sa.Column('nibar', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('kode_register', sa.String(length=32), nullable=False),
    sa.Column('kode_barang_id', sa.Integer(), nullable=False),
    sa.Column('tahun_perolehan', sa.Integer(), nullable=False),
    sa.Column('nilai_perolehan', sa.BigInteger(), nullable=False),
    sa.Column('spesifikasi', sa.Text(), nullable=True),
    sa.Column('jenis_aset', sa.String(length=64), nullable=False),
    sa.Column('judul_buku', sa.String(length=512), nullable=True),
    sa.Column('pencipta_buku', sa.String(length=255), nullable=True),
    sa.Column('spesifikasi_buku', sa.Text(), nullable=True),
    sa.Column('jumlah_barang', sa.Integer(), nullable=False),
    sa.Column('satuan_barang_id', sa.Integer(), nullable=False),
    sa.Column('status_keberadaan', sa.String(length=32), nullable=True),
    sa.Column('jml_keberadaan', sa.Integer(), nullable=True),
    sa.Column('merupakan_atribusi', sa.String(length=8), nullable=True),
    sa.Column('nibar_atribusi', sa.BigInteger(), nullable=True),
    sa.Column('alamat', sa.String(length=512), nullable=True),
    sa.Column('koordinat', sa.String(length=128), nullable=True),
    sa.Column('ruangan_id', sa.Integer(), nullable=True),
    sa.Column('kondisi_barang_id', sa.Integer(), nullable=False),
    sa.Column('merk_type', sa.String(length=255), nullable=True),
    sa.Column('penggunaan', sa.String(length=64), nullable=True),
    sa.Column('nama_kuasa', sa.String(length=255), nullable=True),
    sa.Column('nama_pemakai', sa.String(length=255), nullable=True),
    sa.Column('status_pemakai', sa.String(length=128), nullable=True),
    sa.Column('bast', sa.String(length=8), nullable=True),
    sa.Column('nama_dasar_penggunaan', sa.String(length=255), nullable=True),
    sa.Column('nama_dokumen', sa.String(length=255), nullable=True),
    sa.Column('nibar_tercatat_ganda', sa.String(length=255), nullable=True),
    sa.Column('deskripsi_barang', sa.Text(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('petugas', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kode_barang_id'], ['master_barang.id'], ),
    sa.ForeignKeyConstraint(['kondisi_barang_id'], ['master_kondisi.id'], ),
    sa.ForeignKeyConstraint(['ruangan_id'], ['master_ruang.id'], ),
    sa.ForeignKeyConstraint(['satuan_barang_id'], ['master_satuan.id'], ),
    sa.PrimaryKeyConstraint('nibar')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_item')
    op.drop_table('master_satuan')
    op.drop_table('master_ruang')
    op.drop_table('master_kondisi')
    op.drop_table('master_barang')
    # ### end Alembic commands ###
